### ISSUE TITLE
about this theme and added controls in each tabs

### ISSUE THREAD

**Issue by wwwbarnamehadotnet** [EduardoVB/NewTab#2]
hi again and how r u ?,i downloaded last version today and attached a image about this theme right to left in design and run time isssue,maybe this problem was been exist in other themes too but i not checked yet

![bug 1](https://user-images.githubusercontent.com/12879605/203472050-46c1e471-139b-43c8-ac0e-f8adb91b4c73.png)

i have another simple question about how can i add this grouped controls named 1 or 2 or 3 in tab0 and tab1 and tab2 in design ? or am i should be just use coding for show controls in each tab? i attached a image for my means

i want add group1 in tab 0 and then add group 2 in tab 1 and then add group 3 in tab2 in desiging,i did try for add group 1 in tab0 by desiging and its work but i could not find properties to can active tab 1 in design for  add my group2 in tab1 and then i wanted click on tab 2 for add my group3 .

![2](https://user-images.githubusercontent.com/12879605/203472242-8ca32276-7d42-4df8-99bf-5b74556ac1d6.png)

for better means some thing like this :
![my means](https://user-images.githubusercontent.com/12879605/203477933-b08f5258-e1e8-4025-8b71-beaf3854b566.png)

better animated pic attached about clickable tabs in design time and added controls by easy way :

sample 1 :
![demo](https://user-images.githubusercontent.com/12879605/203477986-675c0f5c-94ab-4d60-957e-1c1d232772ff.gif)

better sample 2 :
![2](https://user-images.githubusercontent.com/12879605/203481001-9c5d6418-dc69-4b54-8024-44d0f73c4243.gif)

**Comment by EduardoVB** [comment]
OK, Issue 1: Problem with themed control in right-to-left: fixed now (I just uploaded a new version). It seems that there is a bug in the API, but I changed something that fixed it.

Issue 2: As I understood, it is about not being able to change the current tab at design time.
This issue only can happen uncompiled, not with the ocx (if I understood it right).

You can change the current tab:
1) From the TabSel property.
2) From the property page Tabs, in 'Current tab', press the arrows.
3) In the NewTab UserControl code, comment the line `#Const NOSUBCLASSINIDE = True`
Then the tabs will become clickable at design time.
But be aware that doing so, you will be enabling subclassing in the IDE, and it could be more prone to crashes (for example pressing the stop button while a form with a NewTab control is opened and possibly doing something).
