### ISSUE TITLE
problem in move controls from each tab to another tab in properties pages

### ISSUE THREAD

**Issue by wwwbarnamehadotnet** [EduardoVB/NewTab#3]
hi, how are u today?
i downloaded last version today and i tested on uncompiled and compiled ocx version and this error : 
[https://i.postimg.cc/JMG53Hxs/error.png](https://i.postimg.cc/JMG53Hxs/error.png)
image link :  [link](https://postimg.cc/BXNbCqS7)

i jast added tab control on form and then i moved a button on tab0 and in properties pages when i enter 0 or 1 button will be move to that tab number but when i enter 2 button not moved to tab2

i guess problem is from last tab number so i not checked more than 3 tabs

**Comment by EduardoVB** [comment]
Fixed, please test.
