### ISSUE TITLE
Change text orientation

### ISSUE THREAD

**Issue by eatornini** [EduardoVB/NewTab#5]
"Hello, when changing the orientation of the tabs to the left, is it also possible to change the text orientation so that it appears in horizontal mode? Thank you very much."

![Sin título](https://github.com/EduardoVB/NewTab/assets/39058755/52971c9b-6367-4ecc-a0e4-a48a8ee6087e)

**Comment by EduardoVB** [comment]
Hello, I added the options to display the captions horizontally in the `TabOrientation` property.
Please test and report back. Thanks.

**Comment by eatornini** [comment]
> Hello, I added the options to display the captions horizontally in the `TabOrientation` property. Please test and report back. Thanks.

Works perfectly, thank you very much for your great work.
