### ISSUE TITLE
Align text to the left in vertical tab.

### ISSUE THREAD

**Issue by eatornini** [EduardoVB/NewTab#6]
Dear, is it possible to align the text of the tabs to the left, I can only get them centered? Thank you very much, your work is amazing, long live VB6.

![Sin título](https://github.com/EduardoVB/NewTab/assets/39058755/1c0a0689-ed83-4ea7-8ccf-9b1f439e3fe5)

**Comment by EduardoVB** [comment]
Hello, I added the property CaptionAlignment. Please test.

(Unregister the ocx first, download the new version and register it)

**Comment by eatornini** [comment]
> Hello, I added the property CaptionAlignment. Please test.
> 
> (Unregister the ocx first, download the new version and register it)

Thank you very much, it worked perfectly, it was what I needed.
