### ISSUE TITLE
reverse clicked on tabs at design forms in right to left mode

### ISSUE THREAD

**Issue by wwwbarnamehadotnet** [EduardoVB/NewTab#7]
hi, When I place the control on the form and align the control's tab layer to the right(righttoleft=true), the tabs are selected incorrectly with a mouse click, it seems like they are clicked in reverse, for example, if I have 5 tabs and they are arranged from right to left, when I click on tab 0, tab number 4 is clicked in the design, or when I click on tab 1, tab number 3 opens, which complicates the task and I cannot place the controls correctly inside the tab.

![bug](https://github.com/user-attachments/assets/b5dd39b9-bba8-49ac-9a87-136e2cfc42ed)

**Comment by EduardoVB** [comment]
Thanks for reporting. Fixed.

**Comment by wwwbarnamehadotnet** [comment]
thanks,can fix these too?
just related to righttoleft mode.

Description in image:
![sstab style halate 2](https://github.com/user-attachments/assets/314c819f-ba68-46a4-b055-efe07891c3be)

better description:
![bug](https://github.com/user-attachments/assets/3efff7bb-a2ca-43f1-ace8-6ab59206fd4e)

**Comment by EduardoVB** [comment]
Hello, thanks. Also fixed.
