### ISSUE TITLE
Tabicons and General tab some issues

### ISSUE THREAD

**Issue by wwwbarnamehadotnet** [EduardoVB/NewTab#8]
HI, when **TDIMode=1 or 2** some options do not show correct in TabIcons and some labels same not show correct or show half:

![tabicons](https://github.com/user-attachments/assets/279d8348-8ee6-4dd0-b3c9-976687cbbf15)

In **General Tab** when highlight combo boxes is enabled, mouse click not work correct on combo box  and most times clicked wrong too, just when i use f4 key some combos about highlight will be open with some issue, check this:

![general tab](https://github.com/user-attachments/assets/eb8aaec6-3092-445a-a0ad-ead46e4ea017)

**Comment by EduardoVB** [comment]
Hello,

> when TDIMode=1 or 2 some options do not show correct in TabIcons and some labels same not show correct or show half

That's was (somewhat) on purpose because TDI mode doesn't have some properties. But anyway there are some things that don't seem right there, I'll check. 
The label showing the half is a clear error.

> In General Tab when highlight combo boxes is enabled, mouse click not work correct

Can't replicate here. Maybe your computer is a bit slow? (I'm asking just to understand what may be happening)

**Comment by EduardoVB** [comment]
OK, I updated the control. Fixed the issue of the Icons property page, about the issue in the General property page I still don't know what to do (since I'm not experimenting the issue). Thanks.

**Comment by wwwbarnamehadotnet** [comment]
Thanks again, I understand that for some reason those sections have been disabled, but what I meant by raising the problem was that it would be better if some options in that section were also enabled because in TDM or TFM mode cases it may be necessary to rearrange the icons and some additional settings.

There is also a minor issue with displaying **tab boxes inside property pages**. For example, when righttoleft is set to true, property pages still display tab boxes whose righttoleft is false.

Regarding the combo box problem, it seems that the problem is not due to the system, because if it is a system problem, the same problem should occur for the other combo boxes as well. The difference between those two combo boxes and the others is that they are related to another property page and a separate design has been made for their property page. I guess the reason is because in that property page another property page must be opened and displayed to the user and inside first property page.

**Comment by EduardoVB** [comment]
> because in TDM or TFM mode cases

Sorry, but what are TDM or TFM modes?

>  it may be necessary to rearrange the icons and some additional settings

I would like to know specifically what settings are necessary and in what cases, probably I'm overlooking something.

> There is also a minor issue with displaying tab boxes inside property pages. For example, when righttoleft is set to true, property pages still display tab boxes whose righttoleft is false.

The righttoleft testing I can perform is somewhat limited because I can't put forms and property pages with RightToLeft True here in my Spanish Windows.
I could, but is is a lot of "trouble" because I need to put Windows in a language that I don't understand, like Arabic.

But what do you mean when you say "when righttoleft is set to true", do you mean RightToLeft of the PropertyPage or RightToLeft of the NewTab control?

If you mean that the Newtab controls put inside a PropertyPage don't take the RightToLeft from the ambient, I can't test that, but I could see that they take the Font from the ambient right.

If you mean that setting RightToLeft to True of a NewTab control that is inside a PropertyPage doesn't work, I just tested that and it is working for me:

![imagen](https://github.com/user-attachments/assets/75052c2d-ee46-451f-a8df-e82e29387afc)

> Regarding the combo box problem, it seems that the problem is not due to the system, because if it is a system problem, the same problem should occur for the other combo boxes as well. The difference between those two combo boxes and the others is that they are related to another property page and a separate design has been made for their property page. I guess the reason is because in that property page another property page must be opened and displayed to the user and inside first property page.

The two comboboxes for HightLightMode and HightLightModeTabSel don't work as normal comboboxes but it is "a monstrosity" that I invented with a picturebox named picHighlightDropDown that you can see if you increase the width of the property page:

![imagen](https://github.com/user-attachments/assets/bf9e3008-f244-4c3f-8db0-121dad82d210)

I didn't have a control to display the things as I wanted and had to make that. So maybe it could not be working fine, but I need to be able to reproduce the issue here in order to fix it, or at least to know what to do.

**Comment by wwwbarnamehadotnet** [comment]
> what are TDM or TFM modes?

TDM or TFM same ntTDIModeControls and ntTDIModeForms
 
  

> I would like to know specifically what settings are necessary and in what cases, probably I'm overlooking something

i means these options can be useful for ntTDIModeControls or ntTDIModeForms modes too if you can fix these options too. for example, maybe we need show icons forms with better size or define one custom icon for all forms or hide icons and etc.:

![tab icons](https://github.com/user-attachments/assets/b3b3f821-e205-460f-af4d-efe29a58e59a)
i notified another small bug too with description in image (about righttoleft captions form in tab with numbers).
 
 

> But what do you mean when you say "when righttoleft is set to true"

about tab inside property pages:
 
![righttoleft](https://github.com/user-attachments/assets/31278e88-fff2-47cc-8fea-3bd835fa0e1e)

 
about dropdown problem:
i guess these area codes need to be change. Problem is about something here:

```
Private Sub cboHighlightMode_DropDown()
    Dim iShow As Boolean
    cboHighlightMode.Visible = False
    cboHighlightMode.Visible = True
    
    If picHighlightDropDown.Visible Then
        HighlightDropUp
        If mControlHighlightModeDropDown <> ntHighlightMode Then
            iShow = True
        End If
    Else
        iShow = True
    End If
    If iShow Then
        ShowHighlightModeDropDown ntHighlightMode
    End If
End Sub
Private Sub cboHighlightModeTabSel_DropDown()
    Dim iShow As Boolean
    cboHighlightModeTabSel.Visible = False
    cboHighlightModeTabSel.Visible = True
    If picHighlightDropDown.Visible Then
        HighlightDropUp
        If mControlHighlightModeDropDown <> ntHighlightModeTabSel Then
            iShow = True
        End If
    Else
        iShow = True
    End If
    If iShow Then
        ShowHighlightModeDropDown ntHighlightModeTabSel
    End If
End Sub
Private Sub ShowHighlightModeDropDown(nControl As NTHighlightDropDownControlConstants)
    Dim iCombo As Object
    mControlHighlightModeDropDown = nControl
    If mControlHighlightModeDropDown = ntHighlightMode Then
        LoadHighlightDropDown mHighlightMode
        Set iCombo = cboHighlightMode
    Else
        LoadHighlightDropDown mHighlightModeTabSel
        Set iCombo = cboHighlightModeTabSel
    End If
    picHighlightDropDown.Move cboHighlightMode.Left, iCombo.Top + iCombo.Height
    picHighlightDropDown.Visible = True
    picHighlightDropDown.ZOrder
    tmrPicDropped.Enabled = True
End Sub
Private Sub tmrPicDropped_Timer()
    Dim iHide As Boolean
    If IsMouseButtonPressed(bsMBRight) Then
        iHide = True
    ElseIf IsMouseButtonPressed(bsMBLeft) Then
        Dim iPt As POINTAPI
        Dim iRect As RECT
        GetCursorPos iPt
        GetWindowRect picHighlightDropDown.hWnd, iRect
        
        If (iPt.X < iRect.Left) Or (iPt.X > iRect.Right) Or (iPt.Y < iRect.Top) Or (iPt.Y > iRect.Bottom) Then
            iHide = True
        End If
    End If
    If iHide Then
        HighlightDropUp
    End If
End Sub

Private Sub HighlightDropUp()
    picHighlightDropDown.Visible = False
    tmrPicDropped.Enabled = False
    SetVariablesFromPicHighlightDropDown
    If mControlHighlightModeDropDown = ntHighlightMode Then
        chkHighlightEffect.Enabled = (mHighlightMode <> ntHLNone)
    End If
End Sub
```

as i checked and showed in image and as i can see Dropdown event process ShowHighlightModeDropDown and this 
ShowHighlightModeDropDown will be enable tmrPicDropped as i can see tmrPicDropped.Enabled = True in ShowHighlightModeDropDown so it will be detecting left mouse click too at same time and result will be hide picHighlightDropDown again as you can see in image result:

debug step by step about Dropdown event:
![dropdown](https://github.com/user-attachments/assets/29ef332b-9118-4d42-b748-c8493cf39a2d)

**Comment by EduardoVB** [comment]
Ocx Updated.

> i means these options can be useful for ntTDIModeControls or ntTDIModeForms modes too if you can fix these options too. for example, maybe we need show icons forms with better size or define one custom icon for all forms or hide icons and etc

In ntTDIModeForms the icons are taken from the forms. I fixed the position of the icons that in some themes appeared wrong. Please check now.

> i notified another small bug too with description in image (about righttoleft captions form in tab with numbers).

Also fixed.

> about tab inside property pages

Fixed too.

> about dropdown problem:

The issue didn't happen here, but I changed something that I expect could have resolved the problem.
Look the code inside Private Sub tmrPicDropped_Timer()

```
        If (iPt.X < iRect.Left) Or (iPt.X > iRect.Right) Or (iPt.Y < iRect.Top) Or (iPt.Y > iRect.Bottom) Then
            iHwnd = WindowFromPoint(iPt.X, iPt.Y)
            If (iHwnd <> cboHighlightMode.hWnd) And (iHwnd <> cboHighlightModeTabSel.hWnd) Then
                iHide = True
            End If
        End If
```

The line
        `If (iHwnd <> cboHighlightMode.hWnd) And (iHwnd <> cboHighlightModeTabSel.hWnd) Then`
is new.

I have a question: I see in your screenshots that you have the labels in the property pages in Arabic (or Farsi I'm not sure). How is that? Did you translate every label?
If so, every time I send an update of the property pages you need to manually copy the label captions again...

The changelog:

```
2024-12-11 Fix in pagNewTabGeneral property page for comboboxes handling HightLightMode and HightLightModeTabSel properties, in some situations left clicking was seen twice.
2024-12-11 Fix when RightToLeft = True, for position in tabs captions when TDIMode = ntTDIModeForms, for the number that uniquely identifies a form when its name is repeated (like (1), (2)).
2024-12-11 Fix when RightToLeft = True, for the NewTab controls that appear as samples in pagNewTabIcons, pagNewTabTabs and pagNewTabThemes property pages.
2024-12-11 Fix in position of form icons (that appear in tabs) when TDIMode = ntTDIModeForms.
2024-12-11 Fix in 'Another Dark Button' theme definition.
```

**Comment by wwwbarnamehadotnet** [comment]
The dropdown works better now, although there is still a slight problem with focus, which is not a big deal. It would be better if the tab icons settings for ntTDIModeControls and ntTDIModeForms  Mode  were not hidden. Anyway, thanks for the new update and for the question.

> I have a question: I see in your screenshots that you have the labels in the property pages in Arabic (or Farsi I'm not sure). How is that? Did you translate every label?
> If so, every time I send an update of the property pages you need to manually copy the label captions again..

its Farsi (same persian) and yes, Since you usually change the code, I just replace the code and I have already done the translation once, unless you add a newer control, which I have to translate and add as well.

**Comment by EduardoVB** [comment]
> It would be better if the tab icons settings for ntTDIModeControls and ntTDIModeForms Mode were not hidden. 

Since you are compiling your own version, just comment these lines:

```
    If mTDIMode Then
        picTDICover1(0).Left = 0
        picTDICover1(1).Left = 2520
        picTDICover1(2).Left = 5400
        picTDICover1(0).Height = cboIconAlignment.Top - picTDICover1(0).Top + cboIconAlignment.Height '+ 30
    End If

' and also the following ones:

    For c = 0 To picTDICover1.Count - 1
        picTDICover1(c).Visible = mTDIMode
    Next
    fraPicture.Enabled = Not mTDIMode
    fraPic16.Enabled = Not mTDIMode
    fraPic20.Enabled = Not mTDIMode
    fraPic24.Enabled = Not mTDIMode
    cmdRemoveIconChar.Visible = Not mTDIMode

```

**Comment by wwwbarnamehadotnet** [comment]
I have previously provided a clear explanation of why the part you hide in ntTDIModeForms or ntTDIModeControls mode can have some uses. Perhaps Google Translate cannot convey the meaning completely or accurately and you will get a wrong impression of my text. It is clear that one of the main reasons is that those properties should be hidden, while showing them has no effect on the two mode mentioned states. My intention was not to simply display those features or, better to say, remove them from the hidden mode. My intention was to be able to use those settings for the two modes mentioned above. I have already given an example, but I will mention it again. For example, if the mode was on ntTDIModeForms, we could set the dimensions or change the icon or the alignment mode of the text and icon or use the icon font instead of the icon **for the forms that are going to be opened**. The same example can be given for the ntTDIModeControls mode too.

I mentioned before that I ignored this part because it seems like you have to add some code to solve this situation, while I can't get involved in the complexities of your coding and it will take me a lot of time to complete these parts that you seem to have neglected to complete. In my version, there is no difference from your version, only the language has changed, otherwise the codes,functions,etc... are the same.

I suggest that if you decide to add features or make changes, be sure to consider the above points about those two modes, which are very useful.

**Comment by wwwbarnamehadotnet** [comment]
You don't need to open the comment again and reply, thanks for the efforts you made to fix some of the reported problems and the useful and important point that needed to be said has been mentioned again, hoping to make better and more practical changes :)
Good luck.

**Comment by EduardoVB** [comment]
Hello, I've been busy and couldn't check this for a few days.
I added the event TDIFormsShowTabIcon that allows for more control over the tab icon and its position and size for TDIMode = ntTDIModeForms.

Please check, the ocx is updated.

**Comment by EduardoVB** [comment]
> use the icon font instead of the icon for the forms that are going to be opened

Hello. The TDIFormsShowTabIcon event has been reworked and now it offers full support for icon font.
